name: Upload Python Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Generate changelog
        run: |
          version=${GITHUB_REF#refs/tags/v}
          sed "0,/^## ${version//./\\.}/d;/^## /,\$d" CHANGELOG.md > ${{ github.workspace }}-CHANGELOG.txt
          echo "name=RpgPy $version" >> $GITHUB_OUTPUT
        id: changelog
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.changelog.outputs.name }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
